# Dataloader
train_df: "data/rsna-bone-age/training/train_df.csv"
valid_df: "data/rsna-bone-age/training/valid_df.csv"

# Training parameters
num_epochs: 50
batch_size: 32
learning_rate: 0.0005

# Model
model_name: "resnet18"
checkpoint_path: "output"
pretrained_filename: "data/pretrained_weights/resnet18.pth"
