# parameters
precision: '16-mixed'
run_name: "inceptionv3_prepr_gender_Thver_lrchange"

# Dataloader
image_size: 512
train_df: "data/rsna-bone-age/training/train_preprocessed.csv"
valid_df: "data/rsna-bone-age/training/valid_preprocessed.csv"

# Training parameters
num_epochs: 50
batch_size: 32
learning_rate: 0.0001

# Model
model_name: "inceptionv3_new"
checkpoint_path: "output"
pretrained_filename: "output/inception.ckpt"
