# parameters
precision: '16-mixed'
run_name: "resnet101_preprocessed_450_lr0001"

# Dataloader
image_size: 450
train_df: "data/rsna-bone-age/training/train_preprocessed.csv"
valid_df: "data/rsna-bone-age/training/valid_preprocessed.csv"

# Training parameters
num_epochs: 50
batch_size: 16
learning_rate: 0.0001

# Model
model_name: "resnet101"
branch: "gender"
pretrained: True
checkpoint_path: "output"
pretrained_filename: ""
