# parameters
precision: '16-mixed'
run_name: "inception_gender_full"

# Dataloader
image_size: 512
train_df: "data/rsna-bone-age/training/train_preprocessed.csv"
valid_df: "data/rsna-bone-age/training/valid_preprocessed.csv"

# Training parameters
num_epochs: 50
batch_size: 32
learning_rate: 0.0001

# Model
model_name: "inception_v3"
branch: "gender"
pretrained: True
checkpoint_path: "output"
pretrained_filename: "output/inception.ckpt"
