# parameters
precision: '16-mixed'
run_name: "resnet50_preprocessed_half_data"

# Dataloader
image_size: 512
train_df: "data/rsna-bone-age/training/train_preprocessed.csv"
valid_df: "data/rsna-bone-age/training/valid_preprocessed.csv"

# Training parameters
num_epochs: 50
batch_size: 1
learning_rate: 0.0005

# Model
pretrained_filename: "lightning_logs/gne6asis/checkpoints/epoch=19-step=2620.ckpt"
pdf_filename: "output/discarded.pdf"
