# parameters
precision: '16-mixed'
run_name: "inception_512_split_3_10"

# Dataloader
image_size: 512
train_df: "data/Mexico_private_dataset/train_preprocessed.csv"
valid_df: "data/Mexico_private_dataset/valid_preprocessed.csv"

# Training parameters
num_epochs: 50
batch_size: 16
learning_rate: 0.0001

# Model
model_name: "inception_v3"
branch: "gender"
pretrained: True
checkpoint_path: "output/inception_1024/"
pretrained_filename: "output/inception_512_new_data/epoch=18-step=13338.ckpt"

# Logs
splits_number: 3
splits_training: True
splits_pickle: "data/Mexico_private_dataset/splits_10.pkl"
splits_df: "data/Mexico_private_dataset/mexico_complete_dataset.csv"