
# Dataloader
image_size: 512
train_df: "data/rsna-bone-age/training/train_preprocessed.csv"
valid_df: "data/rsna-bone-age/validation/test_df.csv"
test_df: "data/Mexico_private_dataset/mexico_preprocessed_additional.csv"

# Training parameters
num_epochs: 50
batch_size: 1
learning_rate: 0.0001

# Model
pretrained_filename: "lightning_logs/uvgog0bh/checkpoints/epoch=47-step=1248.ckpt"
pdf_filename: "output/inception_512_finetuned/splits_2_10_mexico.pdf"


## Folds
splits_number: 2
splits_training: True
splits_pickle: "data/Mexico_private_dataset/splits_10.pkl"
splits_df: "data/Mexico_private_dataset/mexico_complete_dataset.csv"